server:
  port: 9111
spring:
  application:
    name: gzepro-predict-service
  profiles:
    include:
      - mybatis
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka/
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true
info:
  application:
    name: ${spring.application.name}
    descript: 第三方的寿命预测服务，在本系统中支持集群部署多个服务，由feign-consume实现负载均衡。
  build:
    groupId: $project.groupId$
    artifactId: $project.artifactId$
    version: $project.version$